<a href="https://colab.research.google.com/github/amitsiwach/PyTorch/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

Core use case -

- replace numpy to use GPU for fast computing
- automatic differention which can help in calculating gradients => you can implimenting ANNs

In [2]:
import torch

import numpy as np

# Tensors

A kind of data structure => multidimensional arrays or matrices
With tensors you enocode all your parameters.


In [3]:
data = [[9, 10],
        [4, 5], 
        [12, 13]]


tensor_data = torch.tensor(data)


print(tensor_data)

print(type(tensor_data))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>


In [4]:
tensor_data[0, 0]

tensor(9)

In [5]:
np_data = np.array([[9, 10],
        [4, 5], 
        [12, 13]])


tensor_data_np = torch.tensor(np_data)


print(tensor_data_np)

print(type(tensor_data_np))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>


In [6]:
ones_like_data = torch.ones_like(tensor_data_np)
ones_like_data

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [7]:
ones_like_data = torch.ones_like(np_data)
ones_like_data

TypeError: ignored

In [8]:
ones_like_data = torch.ones_like(data)
ones_like_data

TypeError: ignored

In [9]:
ones_like_data_random = torch.rand_like(tensor_data_np)
ones_like_data_random

RuntimeError: ignored

In [10]:
ones_like_data_random = torch.rand_like(tensor_data_np, dtype=torch.float)
ones_like_data_random

tensor([[0.0267, 0.4180],
        [0.0717, 0.9543],
        [0.1928, 0.1964]])

In [11]:
shape = (4,3,2)

rand_tensor = torch.rand(shape)
rand_tensor

tensor([[[0.3807, 0.6709],
         [0.9426, 0.2026],
         [0.8128, 0.8490]],

        [[0.7259, 0.7426],
         [0.0096, 0.4390],
         [0.2231, 0.5361]],

        [[0.8001, 0.4514],
         [0.2382, 0.6040],
         [0.6250, 0.8206]],

        [[0.8299, 0.2703],
         [0.9928, 0.5314],
         [0.1052, 0.3251]]])

In [12]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [13]:
rand_tensor.dtype

torch.float32

In [14]:
rand_tensor.device

device(type='cpu')

In [15]:
ones = torch.ones(shape)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [16]:
zeros = torch.zeros(shape)
zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [17]:
ones = torch.ones(shape)
ones*3

tensor([[[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]]])

In [20]:
torch.cuda.is_available()

True

In [19]:
ones.device

device(type='cpu')

In [21]:
current_device = torch.cuda.current_device()

In [22]:
torch.cuda.get_device_name(current_device)

'Tesla T4'

In [23]:
!nvidia-smi

Sun Jan  8 15:10:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [24]:
if torch.cuda.is_available():
  rand_tensor = rand_tensor.to("cuda") 
  print(rand_tensor.device)

cuda:0


# Concat operations -

In [26]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [27]:
torch.cat([ones, ones, ones])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [28]:
torch.cat([ones, ones, ones], dim=1)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# Arithmatic Ops

In [30]:
y = ones @ ones.T # @ is used for matrix multiplication
y

tensor([[2., 2.],
        [2., 2.]])

In [32]:
y = ones.matmul(ones.T)
y

tensor([[2., 2.],
        [2., 2.]])

In [34]:
y = ones * ones # elementwise multiplication
y 

tensor([[1., 1.],
        [1., 1.]])

In [35]:
y = ones.mul(ones)
y 

tensor([[1., 1.],
        [1., 1.]])

In [36]:
fives = ones + 5
fives

tensor([[6., 6.],
        [6., 6.]])

In [37]:
fives.add_(5)

tensor([[11., 11.],
        [11., 11.]])

In [38]:
fives.item()

ValueError: ignored

In [39]:
type(ones)

torch.Tensor

In [40]:
ones_np = ones.numpy()
type(ones_np)

numpy.ndarray

In [41]:
ones_tensor = torch.from_numpy(ones_np)
type(ones_tensor)

torch.Tensor